version: "3.8"

services:

  pg-controller:
    image: golang
    volumes:
      - ./pg_controller:/go/src/pg_controller
    working_dir: /go/src/pg_controller
    command: go run main.go
    environment: 
      DATABASE_URL: postgres://admin:admin@postgres:5432

  translator:
    image: node:12.13-alpine
    volumes:
      - ./translator:/usr/src/app
    working_dir: /usr/src/app
    command: yarn start:dev
    environment:
      NODE_ENV: "staging"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@linux.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - db
      - front
  py-id3:
    build: py-id3/

  postgres:
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

