version: "3.8"

services:

  postgres:
    environment: 
      POSTGRES_USER: admin
      POSTGRES_DB_PASSWORD_FILE: admin

  pg-controller:
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432

  translator:
    environment:
      NODE_ENV: "staging"

  client:
    networks:
     - front
     - workers
    ports:
      - 80:80